# Generated by Django 3.2.6 on 2021-08-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210812_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
