# Generated by Django 3.2.6 on 2021-08-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=12)),
                ('path', models.CharField(max_length=50)),
                ('execution_time', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
