# Generated by Django 3.2.6 on 2021-09-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_logger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='execution_time',
            field=models.FloatField(),
        ),
    ]
