# Generated by Django 3.2.6 on 2021-09-16 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20210916_1313'),
        ('students', '0004_logger'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
    ]
