# Generated by Django 3.2.6 on 2021-09-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_nbu', models.DecimalField(db_column='Currency NBU', decimal_places=4, max_digits=8)),
                ('currency_mono', models.DecimalField(db_column='Currency Monobank', decimal_places=4, max_digits=8)),
                ('currency_privat', models.DecimalField(db_column='Currency PrivatBank', decimal_places=4, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now=True, db_column='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyEUR',
            fields=[
                ('currency_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_apps.currency')),
            ],
            bases=('service_apps.currency',),
        ),
        migrations.CreateModel(
            name='CurrencyRUB',
            fields=[
                ('currency_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_apps.currency')),
            ],
            bases=('service_apps.currency',),
        ),
        migrations.CreateModel(
            name='CurrencyUSD',
            fields=[
                ('currency_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_apps.currency')),
            ],
            bases=('service_apps.currency',),
        ),
    ]
