# Generated by Django 3.2.6 on 2021-08-25 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=8)),
                ('start_year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2021)])),
                ('finish_year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2021)])),
                ('student_quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
