# Generated by Django 3.2.6 on 2021-08-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='group',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='group',
            name='finish_year',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='start_year',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='student_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default='', max_length=8),
        ),
    ]
